CREATE TABLE TicketAttachments (
    AttachmentID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TicketID            NUMBER NOT NULL,
    UploadedByUserID    NUMBER NOT NULL,
    FileName            VARCHAR2(255) NOT NULL,
    FileMIMEType        VARCHAR2(100) NOT NULL,
    FileContent         BLOB NOT NULL,
    UploadDate          DATE DEFAULT SYSDATE NOT NULL,
    FileSize            NUMBER
);

COMMENT ON TABLE TicketAttachments IS 'جدول لتخزين المرفقات المرتبطة بتذاكر الدعم الفني.';

COMMENT ON COLUMN TicketAttachments.AttachmentID IS 'المعرف الرقمي الفريد للمرفق (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketAttachments.TicketID IS 'معرف التذكرة التي يرتبط بها هذا المرفق.';
COMMENT ON COLUMN TicketAttachments.UploadedByUserID IS 'معرف المستخدم الذي قام برفع هذا المرفق.';
COMMENT ON COLUMN TicketAttachments.FileName IS 'اسم الملف الأصلي للمرفق.';
COMMENT ON COLUMN TicketAttachments.FileMIMEType IS 'نوع MIME للملف (مثال: "image/jpeg", "application/pdf").';
COMMENT ON COLUMN TicketAttachments.FileContent IS 'المحتوى الثنائي للملف (يتم تخزينه كـ BLOB).';
COMMENT ON COLUMN TicketAttachments.UploadDate IS 'تاريخ ووقت رفع الملف (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN TicketAttachments.FileSize IS 'حجم الملف بالبايت.';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) لـ TicketID و UploadedByUserID
-- في سكربت منفصل بعد إنشاء جدولي Tickets و Users.
