CREATE TABLE TicketComments (
    CommentID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TicketID        NUMBER NOT NULL,
    UserID          NUMBER NOT NULL,
    CommentDate     DATE DEFAULT SYSDATE NOT NULL,
    CommentText     CLOB NOT NULL,
    IsInternal      NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT ticketcomments_isinternal_ck CHECK (IsInternal IN (0,1))
);

COMMENT ON TABLE TicketComments IS 'جدول لتخزين التعليقات أو الملاحظات المرتبطة بتذاكر الدعم الفني.';

COMMENT ON COLUMN TicketComments.CommentID IS 'المعرف الرقمي الفريد للتعليق (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketComments.TicketID IS 'معرف التذكرة التي يرتبط بها هذا التعليق.';
COMMENT ON COLUMN TicketComments.UserID IS 'معرف المستخدم الذي قام بإضافة هذا التعليق.';
COMMENT ON COLUMN TicketComments.CommentDate IS 'تاريخ ووقت إضافة التعليق (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN TicketComments.CommentText IS 'نص التعليق.';
COMMENT ON COLUMN TicketComments.IsInternal IS 'يحدد ما إذا كان التعليق داخليًا (1) (مرئي للموظفين فقط) أم عامًا (0) (مرئي للعميل والموظفين).';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) لـ TicketID و UserID
-- في سكربت منفصل بعد إنشاء جدولي Tickets و Users.
