CREATE TABLE Departments (
    DepartmentID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    DepartmentName  VARCHAR2(150) CONSTRAINT departments_name_uk UNIQUE NOT NULL,
    DepartmentEmail VARCHAR2(255) CONSTRAINT departments_email_uk UNIQUE
);

COMMENT ON TABLE Departments IS 'جدول لتخزين الأقسام أو الفرق المختلفة التي يمكن أن تُحال إليها التذاكر أو تكون مسؤولة عنها.';

COMMENT ON COLUMN Departments.DepartmentID IS 'المعرف الرقمي الفريد للقسم (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Departments.DepartmentName IS 'اسم القسم أو الفريق (مثال: "الدعم الفني المستوى الأول", "فريق تطوير الشبكات").';
COMMENT ON COLUMN Departments.DepartmentEmail IS 'عنوان البريد الإلكتروني العام للقسم (يمكن استخدامه للتنبيهات أو التواصل).';
