CREATE TABLE Roles (
    RoleID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    RoleName        VARCHAR2(100) CONSTRAINT roles_rolename_uk UNIQUE NOT NULL,
    RoleDescription VARCHAR2(500)
);

COMMENT ON TABLE Roles IS 'جدول لتخزين الأدوار المختلفة للمستخدمين في النظام، والتي تحدد مستوى صلاحياتهم.';

COMMENT ON COLUMN Roles.RoleID IS 'المعرف الرقمي الفريد للدور (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Roles.RoleName IS 'اسم الدور (مثال: "مدير النظام", "موظف دعم", "مشرف").';
COMMENT ON COLUMN Roles.RoleDescription IS 'وصف موجز للدور والصلاحيات التي يمنحها.';
