CREATE TABLE Tickets (
    TicketID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ReferenceNumber     VARCHAR2(20) CONSTRAINT tickets_ref_uk UNIQUE NOT NULL,
    SubmissionDate      DATE DEFAULT SYSDATE NOT NULL,
    SubmittedByUserID   NUMBER,
    CallerName          VARCHAR2(255),
    CallerContactInfo   VARCHAR2(255),
    TicketTypeID        NUMBER NOT NULL,
    TicketStatusID      NUMBER NOT NULL,
    PriorityID          NUMBER NOT NULL,
    DepartmentID        NUMBER,
    Subject             VARCHAR2(500) NOT NULL,
    Description         CLOB,
    AssignedToUserID    NUMBER,
    LastUpdateDate      DATE,
    ClosedDate          DATE
);

COMMENT ON TABLE Tickets IS 'جدول لتخزين معلومات تذاكر الدعم الفني أو الطلبات.';

COMMENT ON COLUMN Tickets.TicketID IS 'المعرف الرقمي الفريد للتذكرة (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Tickets.ReferenceNumber IS 'رقم مرجعي فريد للتذكرة يمكن استخدامه من قبل المستخدمين للإشارة إليها.';
COMMENT ON COLUMN Tickets.SubmissionDate IS 'تاريخ ووقت إنشاء التذكرة (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN Tickets.SubmittedByUserID IS 'معرف المستخدم الذي قام بإنشاء التذكرة (إذا كان مسجلاً في النظام).';
COMMENT ON COLUMN Tickets.CallerName IS 'اسم الشخص الذي أبلغ عن المشكلة أو طلب الخدمة (إذا لم يكن مستخدمًا مسجلاً أو نيابة عن آخر).';
COMMENT ON COLUMN Tickets.CallerContactInfo IS 'معلومات الاتصال الخاصة بمقدم البلاغ (مثل رقم هاتف أو بريد إلكتروني).';
COMMENT ON COLUMN Tickets.TicketTypeID IS 'معرف نوع التذكرة (مثل: مشكلة، طلب خدمة، استفسار).';
COMMENT ON COLUMN Tickets.TicketStatusID IS 'معرف حالة التذكرة الحالية (مثل: جديدة، مفتوحة، قيد المعالجة، مغلقة).';
COMMENT ON COLUMN Tickets.PriorityID IS 'معرف أولوية التذكرة (مثل: عاجلة، متوسطة، منخفضة).';
COMMENT ON COLUMN Tickets.DepartmentID IS 'معرف القسم أو الفريق المسؤول عن معالجة التذكرة.';
COMMENT ON COLUMN Tickets.Subject IS 'عنوان موجز أو موضوع التذكرة.';
COMMENT ON COLUMN Tickets.Description IS 'وصف تفصيلي للمشكلة أو الطلب الموجود في التذكرة.';
COMMENT ON COLUMN Tickets.AssignedToUserID IS 'معرف المستخدم الذي تم تعيين التذكرة إليه لمعالجتها.';
COMMENT ON COLUMN Tickets.LastUpdateDate IS 'تاريخ ووقت آخر تحديث تم على التذكرة.';
COMMENT ON COLUMN Tickets.ClosedDate IS 'تاريخ ووقت إغلاق التذكرة.';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) في سكربت منفصل
-- بعد إنشاء الجداول المرجعية (Users, TicketTypes, TicketStatuses, Priorities, Departments).
-- مثال على قيد مفتاح فريد تم تضمينه مباشرة:
-- CONSTRAINT tickets_ref_uk UNIQUE (ReferenceNumber)
-- تم تضمينه أعلاه بطريقة مختصرة.
-- مثال على قيد NOT NULL تم تضمينه مباشرة:
-- Subject VARCHAR2(500) NOT NULL (تم تضمينه)
