CREATE TABLE Users (
    UserID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    UserName        VARCHAR2(100) CONSTRAINT users_username_uk UNIQUE NOT NULL,
    FullName        VARCHAR2(250) NOT NULL,
    Email           VARCHAR2(255) CONSTRAINT users_email_uk UNIQUE NOT NULL,
    PasswordHash    VARCHAR2(255) NOT NULL,
    RoleID          NUMBER,
    DepartmentID    NUMBER,
    IsActive        NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT users_isactive_ck CHECK (IsActive IN (0,1)),
    CreatedDate     DATE DEFAULT SYSDATE NOT NULL,
    LastLoginDate   DATE
);

COMMENT ON TABLE Users IS 'جدول لتخزين معلومات مستخدمي النظام.';

COMMENT ON COLUMN Users.UserID IS 'المعرف الرقمي الفريد للمستخدم (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Users.UserName IS 'اسم المستخدم الفريد المستخدم لتسجيل الدخول إلى النظام (يفضل أن يكون بالإنجليزية).';
COMMENT ON COLUMN Users.FullName IS 'الاسم الكامل للمستخدم.';
COMMENT ON COLUMN Users.Email IS 'عنوان البريد الإلكتروني الفريد للمستخدم.';
COMMENT ON COLUMN Users.PasswordHash IS 'تجزئة كلمة المرور الخاصة بالمستخدم (لا يتم تخزين كلمة المرور كنص عادي).';
COMMENT ON COLUMN Users.RoleID IS 'معرف دور المستخدم في النظام (لتحديد الصلاحيات).';
COMMENT ON COLUMN Users.DepartmentID IS 'معرف القسم الذي ينتمي إليه المستخدم.';
COMMENT ON COLUMN Users.IsActive IS 'يحدد ما إذا كان حساب المستخدم نشطًا (1) أو غير نشط (0).';
COMMENT ON COLUMN Users.CreatedDate IS 'تاريخ ووقت إنشاء حساب المستخدم (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN Users.LastLoginDate IS 'تاريخ ووقت آخر تسجيل دخول ناجح للمستخدم.';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) لـ RoleID و DepartmentID
-- في سكربت منفصل بعد إنشاء الجداول المرجعية (Roles, Departments).
-- سيتم تحديد ON DELETE SET NULL لـ DepartmentID عند إضافة المفتاح الأجنبي.
