CREATE TABLE TicketStatuses (
    StatusID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    StatusName      VARCHAR2(100) CONSTRAINT ticketstatuses_name_uk UNIQUE NOT NULL,
    IsOpenStatus    NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT ticketstatuses_isopen_ck CHECK (IsOpenStatus IN (0,1)),
    StatusOrder     NUMBER
);

COMMENT ON TABLE TicketStatuses IS 'جدول لتخزين حالات التذاكر المختلفة التي يمكن أن تمر بها التذكرة خلال دورة حياتها.';

COMMENT ON COLUMN TicketStatuses.StatusID IS 'المعرف الرقمي الفريد لحالة التذكرة (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketStatuses.StatusName IS 'اسم حالة التذكرة (مثال: "جديدة", "قيد المعالجة", "مغلقة", "بانتظار الرد").';
COMMENT ON COLUMN TicketStatuses.IsOpenStatus IS 'يحدد ما إذا كانت هذه الحالة تعتبر حالة "مفتوحة" (1) أم "مغلقة" (0).';
COMMENT ON COLUMN TicketStatuses.StatusOrder IS 'رقم يستخدم لترتيب عرض الحالات في القوائم أو التقارير.';
