CREATE TABLE AppNotifications (
    NotificationID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    UserID              NUMBER NOT NULL,
    NotificationType    VARCHAR2(50) NOT NULL,
    MessageText         VARCHAR2(1000) NOT NULL,
    ReferenceID         NUMBER,
    LinkURL             VARCHAR2(500),
    IsRead              NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT appnotifications_isread_ck CHECK (IsRead IN (0,1)),
    CreationDate        DATE DEFAULT SYSDATE NOT NULL,
    ReadDate            DATE
);

COMMENT ON TABLE AppNotifications IS 'جدول لتخزين الإشعارات داخل التطبيق للمستخدمين.';

COMMENT ON COLUMN AppNotifications.NotificationID IS 'المعرف الرقمي الفريد للإشعار (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN AppNotifications.UserID IS 'معرف المستخدم الذي سيتلقى هذا الإشعار.';
COMMENT ON COLUMN AppNotifications.NotificationType IS 'نوع الإشعار (مثال: "TICKET_ASSIGNED", "COMMENT_ADDED", "STATUS_CHANGED").';
COMMENT ON COLUMN AppNotifications.MessageText IS 'نص رسالة الإشعار.';
COMMENT ON COLUMN AppNotifications.ReferenceID IS 'معرف مرجعي للكائن المتعلق بالإشعار (مثلاً، TicketID إذا كان الإشعار يخص بلاغًا).';
COMMENT ON COLUMN AppNotifications.LinkURL IS 'رابط URL يمكن للمستخدم النقر عليه للانتقال إلى الصفحة ذات الصلة بالإشعار.';
COMMENT ON COLUMN AppNotifications.IsRead IS 'يحدد ما إذا كان المستخدم قد قرأ الإشعار (1) أم لا (0).';
COMMENT ON COLUMN AppNotifications.CreationDate IS 'تاريخ ووقت إنشاء الإشعار (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN AppNotifications.ReadDate IS 'تاريخ ووقت قراءة الإشعار من قبل المستخدم.';

-- ملاحظة: سيتم إضافة قيد المفتاح الأجنبي (FOREIGN KEY constraint) لـ UserID
-- في سكربت منفصل بعد إنشاء جدول Users، مع تحديد ON DELETE CASCADE.
