CREATE TABLE TicketTypes (
    TypeID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TypeName        VARCHAR2(100) CONSTRAINT tickettypes_typename_uk UNIQUE NOT NULL,
    TypeDescription VARCHAR2(500)
);

COMMENT ON TABLE TicketTypes IS 'جدول لتخزين أنواع التذاكر المختلفة (مثل: مشكلة، طلب خدمة، استفسار).';

COMMENT ON COLUMN TicketTypes.TypeID IS 'المعرف الرقمي الفريد لنوع التذكرة (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketTypes.TypeName IS 'اسم نوع التذكرة (مثال: "مشكلة فنية", "طلب ميزة جديدة").';
COMMENT ON COLUMN TicketTypes.TypeDescription IS 'وصف موجز لنوع التذكرة والغرض منه.';
