CREATE TABLE Priorities (
    PriorityID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PriorityName        VARCHAR2(100) CONSTRAINT priorities_name_uk UNIQUE NOT NULL,
    PriorityColor       VARCHAR2(20),
    DefaultDurationDays NUMBER
);

COMMENT ON TABLE Priorities IS 'جدول لتخزين مستويات الأولوية المختلفة التي يمكن تعيينها للتذاكر.';

COMMENT ON COLUMN Priorities.PriorityID IS 'المعرف الرقمي الفريد لمستوى الأولوية (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Priorities.PriorityName IS 'اسم مستوى الأولوية (مثال: "عالية", "متوسطة", "منخفضة").';
COMMENT ON COLUMN Priorities.PriorityColor IS 'رمز اللون المرتبط بمستوى الأولوية (لتلوينها في الواجهات، مثال: "#FF0000").';
COMMENT ON COLUMN Priorities.DefaultDurationDays IS 'عدد الأيام الافتراضي المتوقع لحل تذكرة بهذا المستوى من الأولوية (SLA).';
