-- ==== create_ticket_types.sql ====
CREATE TABLE TicketTypes (
    TypeID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TypeName        VARCHAR2(100) CONSTRAINT tickettypes_typename_uk UNIQUE NOT NULL,
    TypeDescription VARCHAR2(500)
);

COMMENT ON TABLE TicketTypes IS 'جدول لتخزين أنواع التذاكر المختلفة (مثل: مشكلة، طلب خدمة، استفسار).';

COMMENT ON COLUMN TicketTypes.TypeID IS 'المعرف الرقمي الفريد لنوع التذكرة (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketTypes.TypeName IS 'اسم نوع التذكرة (مثال: "مشكلة فنية", "طلب ميزة جديدة").';
COMMENT ON COLUMN TicketTypes.TypeDescription IS 'وصف موجز لنوع التذكرة والغرض منه.';
-- ---------------

-- ==== create_ticket_statuses.sql ====
CREATE TABLE TicketStatuses (
    StatusID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    StatusName      VARCHAR2(100) CONSTRAINT ticketstatuses_name_uk UNIQUE NOT NULL,
    IsOpenStatus    NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT ticketstatuses_isopen_ck CHECK (IsOpenStatus IN (0,1)),
    StatusOrder     NUMBER
);

COMMENT ON TABLE TicketStatuses IS 'جدول لتخزين حالات التذاكر المختلفة التي يمكن أن تمر بها التذكرة خلال دورة حياتها.';

COMMENT ON COLUMN TicketStatuses.StatusID IS 'المعرف الرقمي الفريد لحالة التذكرة (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketStatuses.StatusName IS 'اسم حالة التذكرة (مثال: "جديدة", "قيد المعالجة", "مغلقة", "بانتظار الرد").';
COMMENT ON COLUMN TicketStatuses.IsOpenStatus IS 'يحدد ما إذا كانت هذه الحالة تعتبر حالة "مفتوحة" (1) أم "مغلقة" (0).';
COMMENT ON COLUMN TicketStatuses.StatusOrder IS 'رقم يستخدم لترتيب عرض الحالات في القوائم أو التقارير.';
-- ---------------

-- ==== create_priorities.sql ====
CREATE TABLE Priorities (
    PriorityID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PriorityName        VARCHAR2(100) CONSTRAINT priorities_name_uk UNIQUE NOT NULL,
    PriorityColor       VARCHAR2(20),
    DefaultDurationDays NUMBER
);

COMMENT ON TABLE Priorities IS 'جدول لتخزين مستويات الأولوية المختلفة التي يمكن تعيينها للتذاكر.';

COMMENT ON COLUMN Priorities.PriorityID IS 'المعرف الرقمي الفريد لمستوى الأولوية (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Priorities.PriorityName IS 'اسم مستوى الأولوية (مثال: "عالية", "متوسطة", "منخفضة").';
COMMENT ON COLUMN Priorities.PriorityColor IS 'رمز اللون المرتبط بمستوى الأولوية (لتلوينها في الواجهات، مثال: "#FF0000").';
COMMENT ON COLUMN Priorities.DefaultDurationDays IS 'عدد الأيام الافتراضي المتوقع لحل تذكرة بهذا المستوى من الأولوية (SLA).';
-- ---------------

-- ==== create_departments.sql ====
CREATE TABLE Departments (
    DepartmentID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    DepartmentName  VARCHAR2(150) CONSTRAINT departments_name_uk UNIQUE NOT NULL,
    DepartmentEmail VARCHAR2(255) CONSTRAINT departments_email_uk UNIQUE
);

COMMENT ON TABLE Departments IS 'جدول لتخزين الأقسام أو الفرق المختلفة التي يمكن أن تُحال إليها التذاكر أو تكون مسؤولة عنها.';

COMMENT ON COLUMN Departments.DepartmentID IS 'المعرف الرقمي الفريد للقسم (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Departments.DepartmentName IS 'اسم القسم أو الفريق (مثال: "الدعم الفني المستوى الأول", "فريق تطوير الشبكات").';
COMMENT ON COLUMN Departments.DepartmentEmail IS 'عنوان البريد الإلكتروني العام للقسم (يمكن استخدامه للتنبيهات أو التواصل).';
-- ---------------

-- ==== create_roles_table.sql ====
CREATE TABLE Roles (
    RoleID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    RoleName        VARCHAR2(100) CONSTRAINT roles_rolename_uk UNIQUE NOT NULL,
    RoleDescription VARCHAR2(500)
);

COMMENT ON TABLE Roles IS 'جدول لتخزين الأدوار المختلفة للمستخدمين في النظام، والتي تحدد مستوى صلاحياتهم.';

COMMENT ON COLUMN Roles.RoleID IS 'المعرف الرقمي الفريد للدور (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Roles.RoleName IS 'اسم الدور (مثال: "مدير النظام", "موظف دعم", "مشرف").';
COMMENT ON COLUMN Roles.RoleDescription IS 'وصف موجز للدور والصلاحيات التي يمنحها.';
-- ---------------

-- ==== create_users_table.sql ====
CREATE TABLE Users (
    UserID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    UserName        VARCHAR2(100) CONSTRAINT users_username_uk UNIQUE NOT NULL,
    FullName        VARCHAR2(250) NOT NULL,
    Email           VARCHAR2(255) CONSTRAINT users_email_uk UNIQUE NOT NULL,
    PasswordHash    VARCHAR2(255) NOT NULL,
    RoleID          NUMBER,
    DepartmentID    NUMBER,
    IsActive        NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT users_isactive_ck CHECK (IsActive IN (0,1)),
    CreatedDate     DATE DEFAULT SYSDATE NOT NULL,
    LastLoginDate   DATE
);

COMMENT ON TABLE Users IS 'جدول لتخزين معلومات مستخدمي النظام.';

COMMENT ON COLUMN Users.UserID IS 'المعرف الرقمي الفريد للمستخدم (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Users.UserName IS 'اسم المستخدم الفريد المستخدم لتسجيل الدخول إلى النظام (يفضل أن يكون بالإنجليزية).';
COMMENT ON COLUMN Users.FullName IS 'الاسم الكامل للمستخدم.';
COMMENT ON COLUMN Users.Email IS 'عنوان البريد الإلكتروني الفريد للمستخدم.';
COMMENT ON COLUMN Users.PasswordHash IS 'تجزئة كلمة المرور الخاصة بالمستخدم (لا يتم تخزين كلمة المرور كنص عادي).';
COMMENT ON COLUMN Users.RoleID IS 'معرف دور المستخدم في النظام (لتحديد الصلاحيات).';
COMMENT ON COLUMN Users.DepartmentID IS 'معرف القسم الذي ينتمي إليه المستخدم.';
COMMENT ON COLUMN Users.IsActive IS 'يحدد ما إذا كان حساب المستخدم نشطًا (1) أو غير نشط (0).';
COMMENT ON COLUMN Users.CreatedDate IS 'تاريخ ووقت إنشاء حساب المستخدم (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN Users.LastLoginDate IS 'تاريخ ووقت آخر تسجيل دخول ناجح للمستخدم.';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) لـ RoleID و DepartmentID
-- في سكربت منفصل بعد إنشاء الجداول المرجعية (Roles, Departments).
-- سيتم تحديد ON DELETE SET NULL لـ DepartmentID عند إضافة المفتاح الأجنبي.
-- ---------------

-- ==== create_tickets_table.sql ====
CREATE TABLE Tickets (
    TicketID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ReferenceNumber     VARCHAR2(20) CONSTRAINT tickets_ref_uk UNIQUE NOT NULL,
    SubmissionDate      DATE DEFAULT SYSDATE NOT NULL,
    SubmittedByUserID   NUMBER,
    CallerName          VARCHAR2(255),
    CallerContactInfo   VARCHAR2(255),
    TicketTypeID        NUMBER NOT NULL,
    TicketStatusID      NUMBER NOT NULL,
    PriorityID          NUMBER NOT NULL,
    DepartmentID        NUMBER,
    Subject             VARCHAR2(500) NOT NULL,
    Description         CLOB,
    AssignedToUserID    NUMBER,
    LastUpdateDate      DATE,
    ClosedDate          DATE
);

COMMENT ON TABLE Tickets IS 'جدول لتخزين معلومات تذاكر الدعم الفني أو الطلبات.';

COMMENT ON COLUMN Tickets.TicketID IS 'المعرف الرقمي الفريد للتذكرة (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN Tickets.ReferenceNumber IS 'رقم مرجعي فريد للتذكرة يمكن استخدامه من قبل المستخدمين للإشارة إليها.';
COMMENT ON COLUMN Tickets.SubmissionDate IS 'تاريخ ووقت إنشاء التذكرة (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN Tickets.SubmittedByUserID IS 'معرف المستخدم الذي قام بإنشاء التذكرة (إذا كان مسجلاً في النظام).';
COMMENT ON COLUMN Tickets.CallerName IS 'اسم الشخص الذي أبلغ عن المشكلة أو طلب الخدمة (إذا لم يكن مستخدمًا مسجلاً أو نيابة عن آخر).';
COMMENT ON COLUMN Tickets.CallerContactInfo IS 'معلومات الاتصال الخاصة بمقدم البلاغ (مثل رقم هاتف أو بريد إلكتروني).';
COMMENT ON COLUMN Tickets.TicketTypeID IS 'معرف نوع التذكرة (مثل: مشكلة، طلب خدمة، استفسار).';
COMMENT ON COLUMN Tickets.TicketStatusID IS 'معرف حالة التذكرة الحالية (مثل: جديدة، مفتوحة، قيد المعالجة، مغلقة).';
COMMENT ON COLUMN Tickets.PriorityID IS 'معرف أولوية التذكرة (مثل: عاجلة، متوسطة، منخفضة).';
COMMENT ON COLUMN Tickets.DepartmentID IS 'معرف القسم أو الفريق المسؤول عن معالجة التذكرة.';
COMMENT ON COLUMN Tickets.Subject IS 'عنوان موجز أو موضوع التذكرة.';
COMMENT ON COLUMN Tickets.Description IS 'وصف تفصيلي للمشكلة أو الطلب الموجود في التذكرة.';
COMMENT ON COLUMN Tickets.AssignedToUserID IS 'معرف المستخدم الذي تم تعيين التذكرة إليه لمعالجتها.';
COMMENT ON COLUMN Tickets.LastUpdateDate IS 'تاريخ ووقت آخر تحديث تم على التذكرة.';
COMMENT ON COLUMN Tickets.ClosedDate IS 'تاريخ ووقت إغلاق التذكرة.';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) في سكربت منفصل
-- بعد إنشاء الجداول المرجعية (Users, TicketTypes, TicketStatuses, Priorities, Departments).
-- مثال على قيد مفتاح فريد تم تضمينه مباشرة:
-- CONSTRAINT tickets_ref_uk UNIQUE (ReferenceNumber)
-- تم تضمينه أعلاه بطريقة مختصرة.
-- مثال على قيد NOT NULL تم تضمينه مباشرة:
-- Subject VARCHAR2(500) NOT NULL (تم تضمينه)
-- ---------------

-- ==== create_app_notifications_table.sql ====
CREATE TABLE AppNotifications (
    NotificationID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    UserID              NUMBER NOT NULL,
    NotificationType    VARCHAR2(50) NOT NULL,
    MessageText         VARCHAR2(1000) NOT NULL,
    ReferenceID         NUMBER,
    LinkURL             VARCHAR2(500),
    IsRead              NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT appnotifications_isread_ck CHECK (IsRead IN (0,1)),
    CreationDate        DATE DEFAULT SYSDATE NOT NULL,
    ReadDate            DATE
);

COMMENT ON TABLE AppNotifications IS 'جدول لتخزين الإشعارات داخل التطبيق للمستخدمين.';

COMMENT ON COLUMN AppNotifications.NotificationID IS 'المعرف الرقمي الفريد للإشعار (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN AppNotifications.UserID IS 'معرف المستخدم الذي سيتلقى هذا الإشعار.';
COMMENT ON COLUMN AppNotifications.NotificationType IS 'نوع الإشعار (مثال: "TICKET_ASSIGNED", "COMMENT_ADDED", "STATUS_CHANGED").';
COMMENT ON COLUMN AppNotifications.MessageText IS 'نص رسالة الإشعار.';
COMMENT ON COLUMN AppNotifications.ReferenceID IS 'معرف مرجعي للكائن المتعلق بالإشعار (مثلاً، TicketID إذا كان الإشعار يخص بلاغًا).';
COMMENT ON COLUMN AppNotifications.LinkURL IS 'رابط URL يمكن للمستخدم النقر عليه للانتقال إلى الصفحة ذات الصلة بالإشعار.';
COMMENT ON COLUMN AppNotifications.IsRead IS 'يحدد ما إذا كان المستخدم قد قرأ الإشعار (1) أم لا (0).';
COMMENT ON COLUMN AppNotifications.CreationDate IS 'تاريخ ووقت إنشاء الإشعار (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN AppNotifications.ReadDate IS 'تاريخ ووقت قراءة الإشعار من قبل المستخدم.';

-- ملاحظة: سيتم إضافة قيد المفتاح الأجنبي (FOREIGN KEY constraint) لـ UserID
-- في سكربت منفصل بعد إنشاء جدول Users، مع تحديد ON DELETE CASCADE.
-- ---------------

-- ==== create_ticket_attachments.sql ====
CREATE TABLE TicketAttachments (
    AttachmentID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TicketID            NUMBER NOT NULL,
    UploadedByUserID    NUMBER NOT NULL,
    FileName            VARCHAR2(255) NOT NULL,
    FileMIMEType        VARCHAR2(100) NOT NULL,
    FileContent         BLOB NOT NULL,
    UploadDate          DATE DEFAULT SYSDATE NOT NULL,
    FileSize            NUMBER
);

COMMENT ON TABLE TicketAttachments IS 'جدول لتخزين المرفقات المرتبطة بتذاكر الدعم الفني.';

COMMENT ON COLUMN TicketAttachments.AttachmentID IS 'المعرف الرقمي الفريد للمرفق (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketAttachments.TicketID IS 'معرف التذكرة التي يرتبط بها هذا المرفق.';
COMMENT ON COLUMN TicketAttachments.UploadedByUserID IS 'معرف المستخدم الذي قام برفع هذا المرفق.';
COMMENT ON COLUMN TicketAttachments.FileName IS 'اسم الملف الأصلي للمرفق.';
COMMENT ON COLUMN TicketAttachments.FileMIMEType IS 'نوع MIME للملف (مثال: "image/jpeg", "application/pdf").';
COMMENT ON COLUMN TicketAttachments.FileContent IS 'المحتوى الثنائي للملف (يتم تخزينه كـ BLOB).';
COMMENT ON COLUMN TicketAttachments.UploadDate IS 'تاريخ ووقت رفع الملف (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN TicketAttachments.FileSize IS 'حجم الملف بالبايت.';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) لـ TicketID و UploadedByUserID
-- في سكربت منفصل بعد إنشاء جدولي Tickets و Users.
-- ---------------

-- ==== create_ticket_comments.sql ====
CREATE TABLE TicketComments (
    CommentID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TicketID        NUMBER NOT NULL,
    UserID          NUMBER NOT NULL,
    CommentDate     DATE DEFAULT SYSDATE NOT NULL,
    CommentText     CLOB NOT NULL,
    IsInternal      NUMBER(1) DEFAULT 0 NOT NULL CONSTRAINT ticketcomments_isinternal_ck CHECK (IsInternal IN (0,1))
);

COMMENT ON TABLE TicketComments IS 'جدول لتخزين التعليقات أو الملاحظات المرتبطة بتذاكر الدعم الفني.';

COMMENT ON COLUMN TicketComments.CommentID IS 'المعرف الرقمي الفريد للتعليق (مفتاح أساسي، يتم إنشاؤه تلقائيًا).';
COMMENT ON COLUMN TicketComments.TicketID IS 'معرف التذكرة التي يرتبط بها هذا التعليق.';
COMMENT ON COLUMN TicketComments.UserID IS 'معرف المستخدم الذي قام بإضافة هذا التعليق.';
COMMENT ON COLUMN TicketComments.CommentDate IS 'تاريخ ووقت إضافة التعليق (افتراضيًا تاريخ النظام الحالي).';
COMMENT ON COLUMN TicketComments.CommentText IS 'نص التعليق.';
COMMENT ON COLUMN TicketComments.IsInternal IS 'يحدد ما إذا كان التعليق داخليًا (1) (مرئي للموظفين فقط) أم عامًا (0) (مرئي للعميل والموظفين).';

-- ملاحظة: سيتم إضافة قيود المفاتيح الأجنبية (FOREIGN KEY constraints) لـ TicketID و UserID
-- في سكربت منفصل بعد إنشاء جدولي Tickets و Users.
-- ---------------

-- ==== add_foreign_keys.sql ====
-- Foreign Keys for Tickets table
ALTER TABLE Tickets ADD CONSTRAINT FK_Tickets_SubmittedByUser FOREIGN KEY (SubmittedByUserID) REFERENCES Users(UserID);
ALTER TABLE Tickets ADD CONSTRAINT FK_Tickets_TicketType FOREIGN KEY (TicketTypeID) REFERENCES TicketTypes(TypeID);
ALTER TABLE Tickets ADD CONSTRAINT FK_Tickets_TicketStatus FOREIGN KEY (TicketStatusID) REFERENCES TicketStatuses(StatusID);
ALTER TABLE Tickets ADD CONSTRAINT FK_Tickets_Priority FOREIGN KEY (PriorityID) REFERENCES Priorities(PriorityID);
ALTER TABLE Tickets ADD CONSTRAINT FK_Tickets_Department FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID) ON DELETE SET NULL;
ALTER TABLE Tickets ADD CONSTRAINT FK_Tickets_AssignedToUser FOREIGN KEY (AssignedToUserID) REFERENCES Users(UserID) ON DELETE SET NULL;

-- Foreign Key for Users table
-- Note: FK_Users_Role will be added later after Roles table is created.
ALTER TABLE Users ADD CONSTRAINT FK_Users_Department FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID) ON DELETE SET NULL;

-- Foreign Keys for TicketAttachments table
ALTER TABLE TicketAttachments ADD CONSTRAINT FK_TicketAttachments_Ticket FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID) ON DELETE CASCADE;
ALTER TABLE TicketAttachments ADD CONSTRAINT FK_TicketAttachments_User FOREIGN KEY (UploadedByUserID) REFERENCES Users(UserID) ON DELETE SET NULL;

-- Foreign Keys for TicketComments table
ALTER TABLE TicketComments ADD CONSTRAINT FK_TicketComments_Ticket FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID) ON DELETE CASCADE;
ALTER TABLE TicketComments ADD CONSTRAINT FK_TicketComments_User FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL;

-- Reminder: Ensure that the referenced tables (Users, TicketTypes, TicketStatuses, Priorities, Departments, Tickets)
-- and their primary key columns are created before running this script.
-- The FK for Users.RoleID referencing a Roles table is intentionally omitted as per problem description.
-- ---------------

-- ==== alter_users_add_role_fk.sql ====
ALTER TABLE Users
ADD CONSTRAINT FK_Users_Role
FOREIGN KEY (RoleID)
REFERENCES Roles(RoleID);

-- ملاحظة: سلوك الحذف ON DELETE RESTRICT هو السلوك الافتراضي في Oracle
-- إذا لم يتم تحديد ON DELETE SET NULL أو ON DELETE CASCADE.
-- لذلك، لا يلزم كتابة "ON DELETE RESTRICT" صراحة، ولكن تم تضمين هذه الملاحظة للتوضيح.
-- إذا كان الدور مرتبطًا بأي مستخدمين، فلن يتم السماح بحذف الدور.
-- ---------------

-- ==== alter_appnotifications_add_fk.sql ====
ALTER TABLE AppNotifications
ADD CONSTRAINT FK_AppNotifications_User
FOREIGN KEY (UserID)
REFERENCES Users(UserID)
ON DELETE CASCADE;

-- ملاحظة: ON DELETE CASCADE يعني أنه عند حذف مستخدم من جدول Users،
-- سيتم حذف جميع الإشعارات المرتبطة بهذا المستخدم تلقائيًا من جدول AppNotifications.
-- يجب استخدام هذا السلوك بحذر والتأكد من أنه يتوافق مع متطلبات العمل.
-- ---------------

-- Create Sequence for Ticket Reference Numbers
CREATE SEQUENCE Tickets_RefNum_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- ---------------
